### PR TITLE
Ethereal

### LINKED ISSUE #26: authentication fails when server reply is missing space after 334 code
Colombe throws after trying to start authentication when using ethereal.email service. The same authentication succeeds when using GMail or Mailtrap where you have something like:
```
main.exe: [DEBUG] Clean internal buffer to start TLS.
main.exe: [DEBUG] Start TLS.
main.exe: [DEBUG] <= "EHLO inbox.mailtrap.io\r\n"
main.exe: [DEBUG] => "250-mailtrap.io\r\n250-SIZE 5242880\r\n250-PIPELINING\r\n250-ENHANCEDSTATUSCODES\r\n250-8BITMIME\r\n250-DSN\r\n250 AUTH PLAIN LOGIN CRAM-MD5\r\n"
main.exe: [DEBUG] <= "AUTH PLAIN\r\n"
main.exe: [DEBUG] => "334 \r\n"
```

In ethereal.email you have:
```
main.exe: [DEBUG] Clean internal buffer to start TLS.
main.exe: [DEBUG] Start TLS.
main.exe: [DEBUG] <= "EHLO ethereal.email\r\n"
main.exe: [DEBUG] => "250-smtp.ethereal.email Nice to meet you, 178-83-55-11.dynamic.hispeed.ch\r\n250-PIPELINING\r\n250-8BITMIME\r\n250-SMTPUTF8\r\n250 AUTH LOGIN PLAIN\r\n"
main.exe: [DEBUG] <= "AUTH PLAIN\r\n"
main.exe: [DEBUG] => "334\r\n"
email-test: internal error, uncaught exception:
            (Failure "Sending email failed, Unexpected char: 0d")
```

The issues seems to be that ethereal.email is missing space after 334 code that causes the code to fail as it receives `\r` (0d) while expecting space. Is this bug in Colombe when it fails, if that space is missing or is this bug in ethereal.email service not having it?

### PR DESCRIPTION
**Pull request by dinosaure**
This PR should fix #26. /cc @mikonieminen can you test this PR with `etheral.email`? You should not have any problem.

### CODE REVIEW

File: src/reply.ml [hunk 1]
```diff
@@ -252,8 +252,10 @@ module Decoder = struct
         else
           let k code' decoder = go code code' [ Bytes.sub_string raw_crlf off (len - 2) ] decoder in
           number k decoder
-      | Some chr ->
-        leave_with decoder (`Unexpected_char chr)
+      | Some _ ->
+        let raw_crlf, off, len = peek_while_eol decoder in
+        let reply = v code [ Bytes.sub_string raw_crlf off (len - 2) ] in
+        decoder.pos <- decoder.pos + len ; k reply decoder
```
Comment (mikonieminen) [inline src/reply.ml:258]: This would allow any garbage with after the code (unless the protocol expects something specific). Maybe we should simply check if there is just space missing and we receive `\r\n`.

I played a bit with the code and maybe we could have something like:
```
        let raw_crlf, off, len = peek_while_eol decoder in
        if chr == '\r' && (Bytes.get raw_crlf (off+1)) == '\n'
        then
          let reply = v code [ Bytes.sub_string raw_crlf off (len - 2) ] in
          decoder.pos <- decoder.pos + len ; k reply decoder
        else
          leave_with decoder (`Unexpected_char chr)
```
I suppose my code is a bit ugly way of doing it, but you probably know cleaner way. Like I said, I'm still learning ocaml.

File: test/test_sendmail.ml [hunk 2]
```diff
@@ -255,11 +255,41 @@ let test_6 () =
...
+  let fiber = Sendmail.sendmail
+      unix rdwr () ctx
+      ~domain:(Colombe.Domain.Domain [ "ethereal"; "email" ])
+      (Rresult.R.get_ok @@ Colombe_emile.to_reverse_path romain_calascibetta)
+      [ Rresult.R.get_ok @@ Colombe_emile.to_forward_path anil ]
+      (fun () -> unix.return None) in
+  match Unix_scheduler.prj fiber with
+  | Error err -> Fmt.failwith "Got an error: %a" Sendmail.pp_error err
+  | Ok _ -> is_empty ()
+
```
Comment (mikonieminen) [inline test/test_sendmail.ml:286]: Maybe also add a test that makes sure we allow only missing space and not just any random junk.
